# Default profile (local development and testing)
server:
  port: 8082  # Port for Wallet Service

spring:
  profiles:
    active: default

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb  # Dedicated database for Wallet Service
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # Disable open-in-view to avoid potential performance issues

  # RabbitMQ settings if Wallet Service needs to communicate with other services
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Logging level for the Wallet Service
logging:
  level:
    com.jack.walletservice: INFO

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

# Security settings specific to the Wallet Service
app:
  jwtSecret: Xb34fJd9kPbvmJc84mDkV9b3Xb4fJd9kPbvmJc84mDkV9b3Xb34fJd9kPbvmJc84
  jwtExpirationMs: 3600000

security:
  authentication:
    enabled: true  # Enable authentication for Wallet Service

# Docker profile (for running in containers)
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/walletdb  # Database connection for Docker environment
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # Disable open-in-view in Docker as well

# Logging level for the Wallet Service
logging:
  level:
    com.jack.walletservice: INFO

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

# Security settings specific to the Wallet Service
app:
  jwtSecret: Xb34fJd9kPbvmJc84mDkV9b3Xb4fJd9kPbvmJc84mDkV9b3Xb34fJd9kPbvmJc84
  jwtExpirationMs: 3600000

security:
  authentication:
    enabled: true  # Enable authentication for Wallet Service
